### ISSUE TITLE
API docs improvements: Cleanup and Organization

### ISSUE THREAD

**Issue by ssimic2** [microsoft/FluidFramework#10052]
https://github.com/microsoft/FluidFramework/issues/8847 story outlines overall goals around improved API documentation. In the first round (captured by this epic) we will focus on general cleanup of API docs and improved organization. 

### Goal: Better Packages and API Organization ###
[fluid-framework](https://github.com/microsoft/FluidFramework/tree/main/packages/framework/fluid-framework) aggregates and re-exports other FF packages. We should understand if this approach scales well, as we are already thinking to support more DDSes than the ones currently listed in the package. Clarity around package structure and hierarchy will help API organization. Also, as a part of a top-level grouping we should look for opportunities to assign category/context to various APIs.
- [x] #10310

### Goal: Fix Broken Links & Incomplete API definitions. ###
We have quite a few broken links and incomplete API definitions. 
- [ ] Broken/incomplete API definitions to be fixed for v1.0. (ticket will contain specific action list)

### Goal: Better API Descriptions ###
It's often useful to mix in basic context or example usage with API reference. Here is one such example: [react-dom-client](https://reactjs.org/docs/react-dom-client.html). DDS API reference could, for example, communicate underlining principles - similar to what redux does with a store here for their [getState](https://redux.js.org/api/store#getState) API. The goal is to make API reference docs an entry point for learning more about the FF system in general.
- [ ] Explore format/tools we can use to better correlate API docs with the rest of the learning material.
- [ ] TBD (based on above ticket)

### Goal: General Clarity/Consistency ###
The general need here is to align our ReadMe-s and source code organization with our API docs, and have general clarity on package maturity, availability & support.
- [ ] Improvements around consistent messaging be fixed for v1.0. (ticket will contain specific action list)
