### ISSUE TITLE
Shared String: Shared Interval Programmability Improvements

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5427]
## Feature
The current shared interval collection api is incomplete. There is a  request to improve the api and expose the necessary functionality for a complete Api:

### Programmability Improvements
- [x] #6832: Change properties of an interval via API
- [x] #6111: Event on property changes on shared intervals
- [x] #6107: Ability to iterate over shared intervals; forward and backward 
- [x] #6108: get and remove interval based on an id

### Functional Improvements
- [x] #6109: Support multiple intervals on a range; could be the same physical interval with multiple property bags
- [x] #6110: Support well nested and non-well nested intervals
- [x] #6122 move ends of interval; no insert and delete so change coalesce
- [ ] #6121 Control stickiness of interval ends at shared string modification time
- [x] #9680
- [x] #9310

**Comment by anthony-murphy** [comment]
rough prioritization:

Top:
-	Programmability: Ability to iterator over shared intervals
-	Programmability: get and remove interval based on an id
-	Functionality: Support multiple intervals on a range
-	Functionality: Support well nested and non-well nested intervals

Next:
-	Programmability: Event on property changes on shared intervals
-	Move ends of interval (no insert and delete so change coalesce)

Last:
-	Control stickiness of interval ends at shared string modification time

fyi @curtisman
