### ISSUE TITLE
Support Client Providing Protocol Tree in Summaries and Server-Side Verification

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5771]
## Feature
Currently the protocol tree is generated and controlled by the server. This can create issues if the server and client are uncoordinated due to other issues. This can lead to divergent quorums which can cascade into a lot of issues, including permanent data corruption.

The current design also forces the ordering service (scribe) to make addition storage calls to write the protocol tree, which adds complexity. 

The proposal here is that the when the client generates its summary, it should also include the protocol tree. On receipt of the summary the server should verify the protocol tree. Specifically, the attributes and the quorum members. If the protocol trees do not match the server should close the entire session, and force all clients to rejoin.
## Work items
- [x] #5900 - add flag
- [x] #5901 - check flag in scribe
- [x] #5902 - client set flag and upload protocol
- [x] #8079
- [x] #8080
- [ ] #5903 - scribe validate protocol
- [x] #7102 
- [x] #6451 

``` JSON
".protocol": {
    "id": "bOwAAAAAmDwAABwAAAA==",
    "blobs": {
        "attributes": {
            "branch": "Phjp8QIMYj%2FE1r3o2haqYmnc4VH0%2FzGVqpkRKYGblh4%3D",
            "minimumSequenceNumber": 3863,
            "sequenceNumber": 3878,
            "term": 1
        },
        "quorumMembers": [
            [
                "ccafe4cb-035a-4ec1-9ea1-df13a91b5325",
                {
                    "client": {
                        "user": {
                            "userId": "da2491f1-4598-4dcd-8e6a-730f3540d2c5"
                        },
                        "permission": [],
                        "details": {
                            "capabilities": {
                                "interactive": true
                            }
                        },
                        "mode": "write"
                    },
                    "sequenceNumber": 3842
                }
            ],
            [
                "e8d622af-7ea9-483d-9428-d4d0fa8341d3",
                {
                    "client": {
                        "user": {
                            "userId": "da2491f1-4598-4dcd-8e6a-730f3540d2c5"
                        },
                        "permission": [],
                        "details": {
                            "capabilities": {
                                "interactive": false
                            },
                            "type": "summarizer"
                        },
                        "mode": "write"
                    },
                    "sequenceNumber": 3871
                }
            ]
        ],
        "quorumProposals": "2-bOwIAAAAmDwAABwAAAA==",
        "quorumValues": "3-bOwMAAAAmDwAABwAAAA=="
    },
    "commits": {},
    "trees": {}
}
```

**Comment by anthony-murphy** [comment]
@vladsud @tanviraumi @GaryWilber @curtisman @marcmasmsft

**Comment by anthony-murphy** [comment]
Open question, should the server also validate the quorum proposal, as these can influence the code loaded by clients, so could also be considered secutity critical.

**Comment by anthony-murphy** [comment]
Ideally, we can make this very efficient for the server, as scribe should just need to store a single hash for the quorum at each quorum message (join/leave/propose/reject). this can then easily be mapped into based on the attributes sequence number. scribe would then just need to hash the incoming quorum, and compare it to its own hash for the seq. This list should be able to be truncated at least on every summary, possibly on the min seq.

**Comment by vladsud** [comment]
I do not know if we have appetite here, but I'd use the opportunity to remove quorumValues (either completely, or tracking by server) and promote code key to its own value (in some form or shape). This would require (non-back compat) changes, but I believe it's wrong idea to have such a global entity (available to anybody to poke around).

Excluding "code" from server tracking allows summary to overwrite it, simplifying versioning / upgrade story - client may (as part of code proposal "acceptance" flow) change both "code" key and format / contents of summary. This would be "all clients need to reload" event, but it opens more opportunities RE how we handle version bumps.

That all said, we can take it once small step at a time.

Promoting "code" out of quorumValues (and as result - deprecating quorumValues) potentially allows other scenarios. Like storage can use it for their purposes, like keep same extension (.fluid) but customize actions (Open) it takes on a file.

**Comment by tanviraumi** [comment]
Just to clarify, the proposal is to upload the ".protocol" tree along with the app summary. And then when scribe sees the summary op, it will download the ".protocol" and match with its own in memory state? If they matches, scribe commits it immediately. Otherwise, it nacks and closes the session?

Did not get the hashing part. Are we suggesting scribe to keep a rolling hash of its protocol state. And then when it sees a summary op, it downloads the .protocol field and apply the same hash to match? Or scribe does not download and client sends the hash as a payload of summary op?

I am always in favor of server validating the code proposal. But I am not sure how to enforce this given we don't know anything about the application. Also with the detached creation mode, are we using code proposals anymore? Or it's there to facilitate version upgrade scenario in the future?

**Comment by anthony-murphy** [comment]
@vladsud I agree. I also don't think its that bad right now. I think quorum could easily just become a specialized structure that only support `code` for now. If we need a generalized quorum we could easily add it as a dds. 

@tanviraumi yes. that sounds right. 

My though was that scribe tracks the rolling hash, and matches it to a hash of the protocol it computes. This gives us the most similar guarantees to what we have now.

We still use code proposal, not much has really changes. Right now the only server validation we would get is that that the summarizer didn't unilaterally change it, as scribe would also compute it base on quorum proposals/ops.

**Comment by tanviraumi** [comment]
@anthony-murphy Great! I am imagining scribe will check the entire .protocol field, which will include quorum proposals and values as well.

Let's take the rolling hash as a future work item.

**Comment by anthony-murphy** [comment]
@tanviraumi and @GaryWilber what's the best way to start staging this work? will the server support the client sending the protocol tree right now? what will scribe do? Trying to think about how to break this work down, and start getting pieces of it scheduled

**Comment by tanviraumi** [comment]
Thinking out loud, I think the steps roughly look like the following:

1) Add a flag (I prefer an object with flag as a field for future changes) to ISummaryContent (https://github.com/microsoft/FluidFramework/blob/main/server/routerlicious/packages/protocol-definitions/src/protocol.ts#L183). Flag will be true for requests where .protocol was already uploaded by the client.

2) Scribe needs to be updated to check the flag and for now, ignore the ".protocol" part of the client tree where flag is set to true.

3) Client will start uploading ".protocol" and set flag to true.

4) Scribe can now run validation. if .protocol validation passes, it does not re-upload the same thing anymore and just commits the summary (this part is different between push and r11s since r11s always adds .logTail and .serviceProtocol but that part is already abstracted). If validation fails, it starts nacking.

This should conclude the work. And then we start implementing the rolling hash.

P.S: scribe can combine step 2 and 4 do everything in one PR, assuming clients will start uploading summary soon. But it feels cleaner to me doing in two separate steps. @GaryWilber thoughts?

**Comment by GaryWilber** [comment]
@tanviraumi 2 and 4 in a single PR sounds fine. I think we could finish those before the client finishes number 3.
Do you imagine adding that new flag/field as a param in the [writeClientSummary](https://github.com/microsoft/FluidFramework/blob/5a7f48d9fec84f9ed195ca331e5cb397079e1307/server/routerlicious/packages/lambdas/src/scribe/interfaces.ts#L39) method?

@marcmasmsft Do we need to change anything in the snapshot api for clients to start including protocol in their tree?
I think the clients request will end up looking just like the container snapshot that the create new flow / Push's container request make today. And when push sees this new flag, it will validate the protocol tree and run the container request without adding anything new. The container request would just take in a handle to the client commit

**Comment by tanviraumi** [comment]
The method takes the 'op' already as a param. So we can just extract the flag from it. Yeah combining 2 and 4 sounds fine to me as well. We can even combine 1, 2, and 4 and just run ahead of client. Should be easy to make it back and forward compatible.

**Comment by anthony-murphy** [comment]
I went ahead and created an item for each part of the plan: 
- [ ] #5900
- [ ] #5901
- [ ] #5902
- [ ] #5903

**Comment by anthony-murphy** [comment]
@tanviraumi  and @GaryWilber I've been looking into the client side portion of this, and i'm wondering how important the flag in the summary op is which was added here: #5909, alternately, is this a permanent thing, or just something for staging while we roll this out?

 I ask, as i think we can handle most of this at the loader layer if the op isn't super important, which right now seems like a cleaner design, as then i don't need to pass down a bunch of stuff into the runtime to generate the protocol tree.

**Comment by tanviraumi** [comment]
The flag was mostly for staging. A quick way for server to know whats coming. But r11s can live without it since we download the top level tree anyway and can check whether ".protocol" already exists. Not sure whether Push does the same. FYI @GaryWilber

**Comment by anthony-murphy** [comment]
great. i can def get it there for staging, but it will break the separation of concerns in the design i'm considering. Also, do we have a plan for server side support? I'd like to start testing, ideally with local-server or tinylicious

**Comment by anthony-murphy** [comment]
@GaryWilber could you let me know if the flag in the op is really needed. I've been doing some testing with odsp driver, and it seems to just work. If we don't need to flag, then staging is basially a no-op. i can just push a new loader with no runtime changes, and as that gets picked up, clients will start sending protocol trees

**Comment by GaryWilber** [comment]
@anthony-murphy I think we would want the flag. Today Push will always add the protocol tree to the commit. The flag would instruct us to stop doing that and instead validate what the client provided. Did you test it on a real SPO file and it worked?

**Comment by vladsud** [comment]
Note - flush_ops workflow was implemented in https://github.com/microsoft/FluidFramework/pull/7086, so I'm not aware of any work that is required on the client to support this flow. We need to figure out next steps on this journey.
