### ISSUE TITLE
Collection of 1.0 items to consider

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6272]
## Background
The goal of this issue / epic is to track and organize all the potential issues we would want to review, prioritize, and possibly implement for 1.0 release.
Note that 1.0 release is not necessarily tied to particular goal or date (this should be defined outside of this issue). In context of this issue, 1.0 really means long-term support and graduation of "beta". Today, while we do our best to maintain APIs and behaviors (including back compatibility in document file format), the processes are tight to internal requirements (for example, we assume that new releases are consumed by all customers quickly and get to 99.99% saturation within ~month timeframe in production). We also keep changing and deprecated APIs with assumption that few consumers are using (i.e. we bake into calculus certain collective cost of changing APIs that is based on few internal users of framework). These assumptions needs to change and "1.0" badge needs to reflect that. There are certain areas where we are not happy with APIs and want to change them before that happens, and thus this issue.

This item is not about tracking any other areas, like reliability or perf, i.e. it's focused on API shape, and promises (including backward compatibility) for the long run.

## Issue list

**New issues to be triages and put under appropriate buckets**
- [x] #8481
- [x] #8482

**Correctness**
- [ ] #5738 - triage: cut - consider adding documentation
- [ ] #6465 - triage: in (October)
- [x] #6069 - triage: cut - pending investigation into nature of fix

**Correctness / op batching** - new epic created
(moved to it's own epic: 
- [ ] #5761 - triage: in process
- [x] #4048
- [x] #3788 - triage: in process
- [ ] #7545 - triage: in

**Channel unification**
- [ ] #3469 - triage: cut - wait for 2.0
- [x] #6571 - triage: in process

**Quorum** - new epic created
- [x] #6274 - triage: in
- [ ] #1539 (Important if 1.0 scenarios include direct Quorum manipulation (not through UpgradeManager)). - triage: cut
- [ ] There is a lot of confusion around Quorum vs. Audience usage, when they get updated, when clientId changes, etc. I believe we need to revisit this area and come up with either plan to make it better, or clear documentation / samples that clearly articulate usage / expectations. Inquiry to couple users (Teams, Bohemia) would be warranted here to solicit feedback. Related issues #5251, #1733 - triage: in - needs more analysis

**Waits should be deleted** - new epic created
- [x] #6188 (consider removing or taking into account disposed states) triage: in
- [ ] #4508 - triage: cut

**Cleanup**
- [ ] #4165 - triage: in - deprecate one by 1.0
- [ ] #2903 - triage: in process
- [x] #6033
- [ ] #3429 - triage: in process
- [ ] #6073 - triage: cut
- [ ] #3631 - triage: cut
- [x] #1038
- [ ] #8013 - triage: in process

**Composability**
- [ ] #4265 (Need to break it into more (actionable) items.) - triage: cut
- [ ] #3484 - triage: cut

**IFluidObject**: - new epic created
- [ ] #2566 - triage: in process
- [x] #3275
- [ ] #3264 - triage: in

**Versioning**
- [ ] #1698 - triage: cut
- [ ] Any work around versioning and back compatibility

## Lower priority issues / potential cut line

**Signals**
- [ ] #6544 - triage: cut
- [ ] #5762 (We need to make a call on direction here. Likely documenting properly current expectations and future next steps is sufficient for 1.0. Having conformance testing to be included into FRS/ODSP stress test would be great.) - triage: cut
- [ ] #682 - triage: cut

**Handles & Requests**
- [x] #1247
- [ ] #6001 - triage: cut
- [ ] #3062 - triage: cut
- [ ] #2781 - triage: cut
- [ ] #4194 - triage: cut
- [x] #455

**Loader**
- [ ] #2465 - triage: in - made this into an epic
- [ ] #5114 (This is more about policies, caching, and consistency than just event.) triage: cut
- [ ] #4519 - triage: cut

**Cleanup**
- [x] #8167
- [ ] #4683 - triage: keep - made this into an epic
- [x] #4540
- [ ] #3929 - triage: keep
- [ ] #4475 - triage: cut
- [ ] #3799 - triage: cut
- [ ] Go through all deprecated APIs and figure a plan to actually remove them. - triage: in

**Other**
- [ ] #3854 - triage: cut
- [ ] #3677 - triage: cut
- [ ] #1357 - triage: cut
- [ ] #5192 (There are references to other items (request, loading data store, etc.)) - triage: cut
- [ ] #4912 (It will be much harder to implement it post 1.0. I.e. can we effort not to fix it now? Ever?) triage: cut
- [ ] #2561 - triage: cut
- [x] #2088
- [x] #1683
- [ ] #193 - triage: cut
- [x] #77
- [ ] #1845 - triage: cut
