### ISSUE TITLE
Permanently delete unreferenced content to reduce Fluid file size and complexity (GC Sweep)

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#6330]
## Work Item
**Describe the outcome you expect**
The GC process marks content as unreferenced so that it does not appear in secondary experiences or search, but the content still exists in the underlying files. This work addresses the removal of the content from the underlying file.

**Approach**
- Content will be deleted 30 days after it was last referenced
- The deletion will be triggered by the client
- Content will be removed from the snapshot first (need more detail here)

**Open questions**
- What metrics can we track to validate that this is having the desired impact on file size and complexity?

**Additional context**

**Acceptance criteria**
- Content over a certain age is removed from the snapshot and underlying file
- Tooling exists to validate data correctness
- Replay tool is updated to do GC every op, reload and compare results
- Tools and processes exist to recover content that is erroneously deleted

April 2022
---
- [x] https://github.com/microsoft/FluidFramework/issues/9569
- [x] https://github.com/microsoft/FluidFramework/issues/9426
- [x] https://github.com/microsoft/FluidFramework/issues/9127
- [x] https://github.com/microsoft/FluidFramework/issues/8859

March 2022
---
- [x] https://github.com/microsoft/FluidFramework/issues/9569
- [x] https://github.com/microsoft/FluidFramework/issues/9355
- [x] https://github.com/microsoft/FluidFramework/issues/9108

February 2022
---
- [x] https://github.com/microsoft/FluidFramework/issues/8607
- [x] https://github.com/microsoft/FluidFramework/issues/9017

January 2022
---
- [x] https://github.com/microsoft/FluidFramework/issues/8747
- [x] https://github.com/microsoft/FluidFramework/issues/8549
- [x] https://github.com/microsoft/FluidFramework/issues/8605
- [x] https://github.com/microsoft/FluidFramework/issues/8608
- [x] https://github.com/microsoft/FluidFramework/issues/8672
- [x] https://github.com/microsoft/FluidFramework/issues/8515

December 2021
---
- [x] https://github.com/microsoft/FluidFramework/issues/7924
- [x] https://github.com/microsoft/FluidFramework/issues/8429
- [x] https://github.com/microsoft/FluidFramework/issues/8412
- [x] https://github.com/microsoft/FluidFramework/issues/7206
- [x] https://github.com/microsoft/FluidFramework/issues/8375
- [x] https://github.com/microsoft/FluidFramework/issues/8304
- [x] https://github.com/microsoft/FluidFramework/issues/8554
- [x] https://github.com/microsoft/FluidFramework/issues/8576

November 2021
---
- [x] https://github.com/microsoft/FluidFramework/issues/8126
- [x] https://github.com/microsoft/FluidFramework/issues/8157
- [x] https://github.com/microsoft/FluidFramework/issues/7222
- [x] https://github.com/microsoft/FluidFramework/issues/7925

October 2021
---
- [x] https://github.com/microsoft/FluidFramework/issues/7491
- [x] https://github.com/microsoft/FluidFramework/issues/7493

September 2021
---
- [x] https://github.com/microsoft/FluidFramework/issues/7129
- [x] https://github.com/microsoft/FluidFramework/issues/7152
- [x] https://github.com/microsoft/FluidFramework/issues/7202
- [x] https://github.com/microsoft/FluidFramework/issues/7203

August 2021
---
- [x] https://github.com/microsoft/FluidFramework/issues/6664
- [x] https://github.com/microsoft/FluidFramework/issues/7131
- [x] https://github.com/microsoft/FluidFramework/issues/7130
