### ISSUE TITLE
Offline blob uploads Phase1 - Support blobs while detached

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#6513]
**Phase1: Support blobs while detached**
- [ ] #6514  Define IDetachedBlobStorage with create/read methods
- [ ] #6515 Plumb IDetachedBlobStorage from host to ContainerStorageAdapter
- [ ] #6516 Use IDetachedBlobStorage to persist create/read blobs when detached.
- [ ] #6517 Tests (incl. mock implementation of Node.js)

**Approach**

**Open questions**

**Additional context**

**Acceptance criteria**
