### ISSUE TITLE
fluidframework.com blog

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#8011]
Draft layout here: <https://agreeable-hill-0eeff5b10-8344.centralus.azurestaticapps.net/posts/fluidframework-1.0/>

List of work item here:

- [ ] Create chronological blog section
- [ ] #8344
- [ ] Design changes: are any needed for the blog section?
- [ ] Create RSS feeds
- [ ] At least 3 blog posts planned

**Comment by skylerjokiel** [comment]
Moved to ADO
