### ISSUE TITLE
Convert APIs which return an IQuorum (getQuorum() and friends) to return an IQuorumClients

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#8044]
This will be a breaking change.

To scope access to `Quorum` proposals, we can convert existing `Quorum`-retrieving API surface to return an `IQuorumClients` instead.

With #8036, partners should have everything they need to proactively migrate away from `Quorum` proposal use -- in which case this will be a no-op change beyond typing fixup.  However, if partners need more time to migrate they can temporarily cast to an `IQuorum` as we won't actually be modifying the runtime object returned.  I don't anticipate this being a common case though.

Alternatively, we could consider adding a pre-deprecated `getLegacyQuorum(): IQuorum` in places next to `getQuorum(): IQuorumClients` which would give us an opportunity to warn and instrument.  Probably only consider this option if it looks like migration will be an issue.

- [x] Convert runtime to return `IQuorumClients` -- #8575
- [x] Convert container definitions to return `IQuorumClients` -- #8638 
- [ ] Convert container implementations to return `IQuorumClients` -- #8880
