### ISSUE TITLE
Get OldestClientObserver ready for production use

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#8088]
Currently, `AgentScheduler` is the only non-experimental solution we provide for task assignment.  `OldestClientObserver` has become an attractive alternative for some customers since it does not persist data or emit ops, and therefore does not necessitate singleton patterns to minimize those COGS costs.

However, `OldestClientObserver` is currently in experimental state.  This issue tracks the known work that is prerequisite to move it to production state.

- [ ] Add tests.
- [ ] Reconcile scenario gap against the shared tree DDS (which wants to use it, but instead duplicates the logic)
- [ ] Split to its own package, as we likely will not have `TaskManager` ready on the same timeline.
- [ ] Incorporate any feedback from early adopters
- [ ] Consider whether we'd want to alter the design to borrow concepts from `OrderedClientElection`/`SummarizerClientElection`.  These replaced the `QuorumHeap` that `OldestClientObserver` was originally based upon.  If `OldestClientObserver` is not robust enough to replace that logic, we should understand why and whether our customers will also need a more robust solution.

**Comment by ChumpChief** [comment]
Tracked in ADO
