### ISSUE TITLE
Explicit read/write mode & transitions for azure-client

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#8857]
This work captures the local connectivity state of a given client and letting the developer control transitions between different states specifically for azure-client.

## Concerns/Thoughts
- This space is not well encapsulated and may make achieving some of these key results impossible without extensive refactoring.

## Key Results
- [ ] Developer can set the state of the user connection when loading a container
- [ ] Developer can understand and transition between states. 
- [ ] Developer can understand how and when to use this functionality 

> Note: Currently the developer can choose if the customer is in read/write mode based on the setting in the Token. This work would allow the developer to more explicitly set the connection state of the client when loading a container.

**Comment by skylerjokiel** [comment]
Moved to ADO
