### ISSUE TITLE
V1 Debugger for azure-client and DDSes 

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#8873]
This work tracks an in memory debugger that showcases a live set of Fluid data. The goal would be for developers to be able to run the debugger locally in the browser and it would provide realtime insights in to what data is online.

## Key Results
- [ ] Developers can see an MVP set of live data with their debugger

## Data to display
- [ ] SharedMap
- [ ] SharedString
- [ ] Tree view of all data based from the initial objects 
- [ ] Audience
- [ ] Connectivity state
- [ ] read/write mode state

## Features
- [ ] Data in the tool can be modified

**Comment by skylerjokiel** [comment]
Moved to ADO
