### ISSUE TITLE
Drive Real Service and Stress Tests Errors to Zero

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#8942]
We've done some work to drive our stress test errors down the rest of the issues are filed under this query:
https://github.com/microsoft/FluidFramework/issues?q=is%3Aopen+is%3Aissue+label%3A%22src%3A+stress+tests%22

Additionally, our end to end test log a number of errors. Some of these errors are expected, but some are not, and it is hard to differentiate between the two. In order to increase our signal to noise ratio in our tests we need to differentiate, and handle expected vs non-expected errors.

In general, the best way to increase our signal to noise ratio in our test telemetry would be to not log expected errors. This will leave only unexpected errors in our error tables.

There are a few ways to accomplish this, but in general it will be necessary for test that expect errors to be annotated in a way such that those expected errors can be excluded from our error tables. This in itself may be enough, but it will leave us to find all regression via telemetry after checkin, which is a more costly way to find and fix issues.

So in addition to the above, we should update our end-to-end test infra to fail tests if any unexpected errors are seen. This will  cause tests to fail during development, and in our buddy build if unexpected error occurs. It will also act as a forcing function to keep our tests, and test telemetry is a healthy state. Ideally, we would such functionality would have the following properties:

- Test failures based on unexpected errors occur after the test has completed
- Test failure fail only the test, and not the test suite
- Expected errors are easy to specify, but specific enough to prevent suppressing unexpected errors.

The reasoning for these properties is based on how we use our end-to-end tests. We run them against a number of servers. In the gate we only run against local-server, but in our CI we also run tinylicious, odsp, and Frs. Because of this, we should not reduce coverage based on unexpected errors, by failing tests midway through, or failing test suites. Additionally, we don't generally expect 100% pass rates for our test against real services due to the variable nature of running against external machines over the network. So we want unexpected errors to be logged as many times as they occur to make it easier to detect true regressions via telemetry.

In terms of error suppression, we should leverage our existing telemetry event object. Via some api test should specify the shapes of their expected error via telemetry event object. We likely don't want to limit this to only error event, such that tests can use the same functionally it very other events have occurred. 

## Stress Issues:
 - [x] #9064 
 - [x] #8668 
 - [x] #8665
 - [x] #6689
 - [x] #6083 

### Multiple Drivers:
- [x] #9039
- [x] #9040

### Tinylicious
- [x] #9238
- [ ] https://github.com/microsoft/FluidFramework/issues/9372
- [ ] https://github.com/microsoft/FluidFramework/issues/9371

### ODSP, R11s, and FRS
-  [ ] Errors needs investigation of errors

**Comment by anthony-murphy** [comment]
https://github.com/microsoft/FluidFramework/issues?q=is%3Aopen+is%3Aissue+label%3A%22src%3A+stress+tests%22

**Comment by anthony-murphy** [comment]
https://github.com/microsoft/FluidFramework/issues/9039
https://github.com/microsoft/FluidFramework/issues/9040

**Comment by markfields** [comment]
A bunch more tracked in this uber issue #9534, as we are disabling a bunch of tests to get a clean baseline for better regression detection.

**Comment by anthony-murphy** [comment]
I think that is a bit different. this is specifically around telemetry errors. not test failures. there is some overlap, but they are not 1-1

**Comment by anthony-murphy** [comment]
adding good first issue here as it shouldn't be to hard to grab individual issue above to work on for those new to the code base. at minimum there is a test that can be debugged and worked through.
