### ISSUE TITLE
Automate change integration from current version to next version dev branches

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#9296]
Under the "main" and "next" model, changes from main can be bulk integrated to next every once in a while.  This however opens the possibility of merge conflicts that whoever is doing the integration will need to resolve.  This should instead be the responsibility of the original change author because they have the correct context to do the merge resolution.

# Issues

- [x] #9867

## April 2022
- [x] #9855

## May 2022
- [x] #9868
- [x] #9992
- [x] #9869
- [x] #9866
- [x] #10219
- [ ] #10254
- [x] #10255
- [x] #10311
- [x] Retrieving commit from Azure Queue
- [x] Open PR to check merge conflicts and CI run with next branch
- [x] Bot to merge PR in next branch
- [x] #10256
- [x] #10257

## Next 
- [x] #9865

# Notes
- We probably want some way for a developer to choose to bring a change into `next`'s history/indicate it's been accounted for in some way without actually merging the change contents/skip the automatic merge entirely.  For example, for features that receive both compatible and breaking implementations across the two branches, the developer may want to not bring the changes from `main` to `next` at all.  Or for some mechanical repo changes to package.jsons, they might be fully resolved as part of resolving merge conflicts but the whole merge could be skipped entirely.

**Comment by Abe27342** [comment]
@sonalivdeshpande given your recent changes in this area, does it make sense to close this?

**Comment by sonalideshpandemsft** [comment]
yep. this can be closed
