### ISSUE TITLE
Review use of node APIs

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#9506]
This issue is to track the work related to fully addressing #8725. I'm opening a new issue since #8725 has a lot of discussion on it already.

## Issues

- [x] #9508
- [x] #4843
- [x] #9443
- [x] #10225

### Next
- [ ] Review list and decide, for each, what the "policy" should be for the library.
- [ ] Look at complete dependency chain for the 3P libraries and ensure they're all implicit-dependency free.
- [ ] Use the `browser` field instead of `main` for packages that are intended to run in the browser (e.g. examples, anything that uses webpack in the build).

## Policy options

1. We shouldn't use the library -- either replace it with an isomorphic implementation, add explicit polyfill dependencies, or remove usage completely.
2. Using the library in test code is ok. Usage of the node libraries should be explicitly identified.

**Comment by tylerbutler** [comment]
Closing since most if not all of this work has been done.
