### ISSUE TITLE
Demo of how to perform data migration across breaking changes using export/transform/import strategy

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#9717]
- [x] #9096 - #9495
- [x] #10025
- [x] #10026
- [ ] Build migration step for data migration demo that converts from old container code to new container code
- [x] #10027
- [ ] Correctly handle disconnection scenarios
- [ ] Make the demo work with Azure
- [ ] Refine demo and incorporate feedback (potentially including work to improve the integration and/or encapsulation of the constituent mechanisms)

**Comment by ChumpChief** [comment]
This is sufficiently tracked in ADO
