### ISSUE TITLE
Improve, normalize, and streamline the experimental package experience

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#9885]
We currently use the `@fluid-experimental` package scope to denote packages that are ready for trial but not production use.  This is a useful tool for publishing ideas for customer feedback.

However, there are some rough edges.  This issue tracks areas for improvement.

- [ ] Standardize experimental package location (e.g. under /experimental or under expected final position)
- [ ] Ensure experimental package documentation clearly notes the experimental status
- [ ] Standardize README content for experimental packages to clearly note the experimental status
- [ ] Document and publish support/compat policy for experimental packages
- [ ] Stop generating type tests for experimental packages
- [ ] Audit existing experimental packages to either remove or make a plan for advancing to production
- [ ] Consider `npm i` messages on install of an experimental package
- [ ] Consider only publishing experimental packages "on demand" rather than on every version
- [ ] Consider an extra developer step to enable experimental packages that would make them unusable in production for the general public (e.g. setting a value in localStorage)

**Comment by ChumpChief** [comment]
Tracked in ADO, closing
